### ISSUE TITLE
All tile entities are broken

### ISSUE THREAD

**Issue by Terifiel** [MicleBrick/ExplosionRegen#11]
The inventory of a placed shulker box isn't restored when the plugin restores destroyed blocks

**Comment by rsammelson** [comment]
On 1.15.2, I tested it, and I found a group of similar bugs. Chest inventories don't seem to be restored, sign text isn't restored, and items in a furnace are not restored. I would suggest adding a switch to this to the configuration file if those things are added, as restoring the inventory of a chest goes far beyond just keeping the landscape from becoming full of holes, it actually prevents people from losing their items in chests if they mess up with a creeper.

**Comment by MicleBrick** [comment]
It seems that all tile entities are broken basically. I can make it so there's an option to drop items, but originally, this plugin restored all tile entities including chests. It must've broken at some point, I don't know when and will have to investigate.

**Comment by MicleBrick** [comment]
Update on this: did some fixing, all tile entities appear to work save for chests as of now. Attempting to fix chests, once they're fixed this should be solved

**Comment by MicleBrick** [comment]
would appreciate if anyone has any ideas why the chests items might be clearing after successfully placing the tile entity & verifying that the item is indeed there..
