### ISSUE TITLE
Armor stand is exploded but not regenned

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#14]
armor stands are technically an entity AND a block, but they currently explode and then dont come back which should definitely be fixed.

**Comment by MicleBrick** [comment]
Technically speaking, they're actually only an entity afaik. I'll see if I have time to investigate it. Bit busy with uni these days

**Comment by MicleBrick** [comment]
Apparently this is just part of #14 so I'll close this

**Comment by MicleBrick** [comment]
by #14 I meant #19 lol

**Comment by MicleBrick** [comment]
On second thought nevermind, it's that the plugin doesn't regenerate entities at all and armor stands are entities, not blocks. When I did #11 I'll try adding a feature to regenerate certain entities like item frames and armor stands with a configurable list
