### ISSUE TITLE
How to configure the config.yml 

### ISSUE THREAD

**Issue by AkhikoFR** [MicleBrick/ExplosionRegen#15]
I really need to configure it but the minecraft server in 1.15.2 rejects it and returns the file to its initial state, here is the information I enter:
(I just want to regen the grass and dirt and stone blocks)

# Time in minutes after exploding blocks should regenerate
regen_delay: 0.1
placement_intensity: 0.1
ignored_entities: 
ignored_materials: 
included_materials: 
 - "grass_block"
 - "dirt"
 - "stone"

Thank you in advance for your help!

**Comment by MicleBrick** [comment]
Hmmm... Any errors?

**Comment by AkhikoFR** [comment]
No, just the file is replaced by the basic file, and does not take into account the configuration

**Comment by AkhikoFR** [comment]
Link with my config in Notepad++ : https://ibb.co/Wf6TxBt

**Comment by MicleBrick** [comment]
One thing I can think of is that you don't have the latest version of it which adds that configuration option in the first place. That would result in this happening. Could you make sure you have the latest version that was released 3 months ago?

**Comment by AkhikoFR** [comment]
I have the version 2.5.0 published in Jan 3, 2020

**Comment by AkhikoFR** [comment]
I understood my mistake, I did not put the name of the blocks in capital! as in this link:
https://papermc.io/javadocs/paper/1.13/org/bukkit/Material.html

Is there a method to exclude all but three blocks?

**Comment by AkhikoFR** [comment]
I managed to do what I wanted, dirt and grass_block and stone that destroyed but not the other blocks, I give the config.yml pastebin for other!

https://pastebin.com/HTV9nda6

**Comment by MicleBrick** [comment]
Is it supposed to regenerate everything except those three materials?

**Comment by AkhikoFR** [comment]
the three blocks this regenerates but not the other blocks!

**Comment by MicleBrick** [comment]
Then shouldn't you set the included materials and leave the ignored materials empty?

**Comment by AkhikoFR** [comment]
If I do this, there’s a problem when a tnt explodes it doesn’t happen anything like I put an explosion-tnt argument: false
