### ISSUE TITLE
Options File Comments

### ISSUE THREAD

**Issue by rsammelson** [MicleBrick/ExplosionRegen#19]
There is an options file in the repository, which has explanations for every parameter, but the default generated options file only has one comment. Can this be fixed so the comments show in the generated file?

**Comment by MicleBrick** [comment]
So the config.yml in the repository has multiple parameters but the generated one doesn't. That's odd, it should be simply loading the provided values into the default config with all the comments and then writing it iirc, I did some weird stuff to make that work though, so it might be broken. I'll look into it when I get a chance, God willing.
