### ISSUE TITLE
Let us decide which type of explosion that regenerates.

### ISSUE THREAD

**Issue by olekristian** [MicleBrick/ExplosionRegen#2]
Hey!
Good job on the plugin, nice to see some up to date fresh plugin. Let me get to the point;

I want to allow TNT explosions without it regenerating, but I'd like creeper explosions to regenerate. 
Consider adding this feature in the config. 

Thanks a lot for your work! 
Kattemannen

**Comment by Miclebrick** [comment]
Sure, that should not be too hard.

**Comment by Miclebrick** [comment]
Implemented but did not yet test. If you want to test it first, here is the jar: https://github.com/Miclebrick/ExplosionRegen/releases/download/v1.1.0/ExplosionRegen-1.1.0.jar
