### ISSUE TITLE
Chest problem

### ISSUE THREAD

**Issue by Skyexir** [MicleBrick/ExplosionRegen#20]
Hello, your super plugin has a problem, the chests have no more objects when they reappear.
It would be cool if at least they drop them : )

**Comment by MicleBrick** [comment]
This is a known bug (#11). I'm very sorry that it's been around for this long, as it's a critical bug, but I'm currently busy with uni to fix it. I plan on fixing it right after final exams.

**Comment by Skyexir** [comment]
Okay no problem i understand, thanks a lot for your support!
