### ISSUE TITLE
Chest contents are not regenerated

### ISSUE THREAD

**Issue by Acervans** [MicleBrick/ExplosionRegen#22]
Hi, I'm not sure if this is intentional, but even lowering the delay to below 5 mins, all content inside the chests disappear completely after regeneration. Is this intended, or is there any way to fix? Thanks

**Comment by MicleBrick** [comment]
Known bug, think there's another issue for it already, I'm gonna fix and post an update this morning God willing

**Comment by Acervans** [comment]
Ok, thanks for the quick reply
