### ISSUE TITLE
Regenerate blocks in order

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#27]
Issue #1, adding block by block placement is a good start. However the main reason to regenerate things piece by piece is to keep players and mobs from getting trapped inside the explosion regen zone and dieing of suffocation. Right now it looks cool, but the blocks seem to regen from closest to the point of explosion to the farthest away from the explosion which almost always ends with anything inside a creeper, ghast, or wither "pit" suffocating because the "ceiling" regenerates before the "floor". This also means anything with gravity that WAS on the surface is now buried and/or glitched under the ground (for example as per #14 armor stands are now regened but sometimes fall into the ground because the blocks they were on did not come back yet).
To make this a more useful feature the blocks need to regenerate in a specific order. From the inside out. Farthest from impact to closest to impact in other words.

**Comment by rsammelson** [comment]
Currently, the blocks are intended to regenerate in order from farthest from the explosion to nearest. If this is not what is actually happening, it must be some sort of bug. I’ll go ahead and take a look at it.

**Comment by MicleBrick** [comment]
fixed in 4.0.0
