### ISSUE TITLE
Incorrect or unclear "regen_delay" and "placement_intensity"

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#28]
The timings set in the config are either unclear or incorrect as when I time it the blocks begin to regen at approximately 24 seconds and finish at around 30 seconds when regen_delay is set to 1.0 (meaning there should be an entire minute before they even start regenerating, and they finish in half of that).
If this is intended then the config should be more clear but I believe this is an error.

**Comment by MicleBrick** [comment]
seems fixed in 4.0.0 by fixing other issues
