### ISSUE TITLE
TNT now regenerates as of version 3.0

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#30]
I do not remember TNT regenerating before. Now with 3.0 and a fresh config TNT and TNT minecarts now regenerate their explosions and I do not see a config option to disable this.
It would be neat to have config options to determine what explosions are or are not regenerated, but at the very least have player created explosions such as TNT should not regenerate by default.

**Comment by MicleBrick** [comment]
There's a config option for this, ignored blocks iirc

**Comment by BornToDoStuff** [comment]
As I understand it that ignores blocks when regenerating explosions, correct?
I mean the explosions themselves regenerate. When I set off TNT it regenerates the same way a creeper would, and that is not wanted functionality, as TNT detonating is an intentional explosion.

**Comment by MicleBrick** [comment]
You can add it to ignored entities iirc

**Comment by BornToDoStuff** [comment]
Adding primed TNT to the ignored entities list does not keep the explosion of the TNT from regenerating. 
TNT explosions are regenerating. Not the blocks, not the entities, all the blocks they explode are.

**Comment by MicleBrick** [comment]
"# Blocks blown up by these entities will not be affected by this plugin"

**Comment by BornToDoStuff** [comment]
You are right, I did misread the config description, however in my config I have "PRIMED_TNT" in the list and it does not effect whether or not the explosions are regenerated.

![image](https://user-images.githubusercontent.com/4149032/85927046-8f1bcb00-b871-11ea-9b45-f154459af202.png)

**Comment by MicleBrick** [comment]
You can do this on 4.0.0 now:
```YAML
# Blocks blown up by these entities will not be affected by this plugin
ignored_entity_explosions:
 - CREEPER
 - PRIMED_TNT
```
