### ISSUE TITLE
1.16.1 Support

### ISSUE THREAD

**Issue by Acervans** [MicleBrick/ExplosionRegen#33]
The plugin doesn't support 1.16.1, explosions behave like normal

**Comment by MicleBrick** [comment]
Thanks for reporting this, I should have this fixed this weekend

**Comment by MicleBrick** [comment]
[ExplosionRegen-4.0.0.zip](https://github.com/MicleBrick/ExplosionRegen/files/4881396/ExplosionRegen-4.0.0.zip)
here's a WIP jar for 1.16.1

**Comment by Acervans** [comment]
I've been using it and seems to be working fine.

**Comment by MicleBrick** [comment]
Cool, thanks. I'll try to get a release out asap. Just been unbelievably busy with work and summer classes :/

**Comment by MicleBrick** [comment]
fixed in 4.0.0
