### ISSUE TITLE
Could Not Load Error Message - Minecraft server version: Paper 1.15

### ISSUE THREAD

**Issue by UndeadWizard** [MicleBrick/ExplosionRegen#35]
https://gyazo.com/f91d5e5b78b148a6b46988d7619ec38a

Getting this error, like the title says.

**Comment by MicleBrick** [comment]
As the error says, the plugin is for 1.16. feel free to use version 3.0 in the releases tab on this repository if you want 1.15

**Comment by MicleBrick** [comment]
(and of course if you know how to program you can just replace the NMSUtils class with the 1.15 NMSUtils one. I might make it automatically select one someday.)

**Comment by UndeadWizard** [comment]
I'd prefer avoiding 3.0 considering that the bugs are precisely the reason why I was hoping that there would be an update fixing those without needing to completely change server versions.

**Comment by MicleBrick** [comment]
There is not. Feel free to try recompiling it for 1.15 if you cannot update for some reason.
