### ISSUE TITLE
block ignore list / chain explosions

### ISSUE THREAD

**Issue by melanite** [MicleBrick/ExplosionRegen#4]
hi!

was wondering if its possible to have an ignore list or support chain explosions from TNT

primed TNT will treat other TNT around it as another block and regen it back.

so far, this is working great for me! thank you a lot.

**Comment by Miclebrick** [comment]
making it ignore certain types of blocks is certainly a possibility

**Comment by Miclebrick** [comment]
Sorry if I take a while to get around to this though, I'm working on some big other projects right now and won't have much time for this for a while. You can most likely count on me doing it reasonably soon though :smiley:
