### ISSUE TITLE
Items dont regen with NBT data.

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#45]
Items with inherent NBT data such as signs, shulker boxes, banners, and paintings, are not regenerated the same way they explode. Shulkers are emptied, paintings randomly re-assigned, sign text is removed, heads become Steve, etc.

A shulker box being emptied could be devastating, so I can't yet use this plugin in good conscience.

*note: this seems heavily related or the same as #38, #40, and #42.*

**Comment by MicleBrick** [comment]
This is because the publicly released version is currently outdated, updating now
